### PR TITLE
update vendored mqtt.js to 4.1.0

### PR DESCRIPTION
**Pull request by nosovk**
Currently there is v.3 version of library bundled, which causes problems in some cases.
Like https://github.com/sclausen/ngx-mqtt/issues/142
We have that issue in some cases, and hope that it caused by BETA status of mqtt5 protocol in v.3 version of libararry

According to https://github.com/sclausen/ngx-mqtt/issues/150 I use
https://unpkg.com/mqtt@4.1.0/dist/mqtt.min.js
to update vendored lib.

### CODE REVIEW

**Comment by sclausen** [comment]
Unfortunately the app doesn't build anymore with the following error.
```
ERROR in ngx-mqtt.min.js from UglifyJs
Unexpected token: punc ()) [ngx-mqtt.min.js:1704,6573]
```

If you could fix this issue, I'm happy to merge.

**Comment by nosovk** [comment]
@sclausen there was some problems with webpack.
I supposed that using old format is obsolete.
In PR build system moved to angular lib.
It builds etc, but I can't fix tests (it seems that they were broken before)
Version provided in PR will work with Angular8+, but on previous versions probably will fail.

**Comment by nosovk** [comment]
Also no need in Vendoring MQTT anymore

**Comment by sclausen** [comment]
Okay, I‘ll have a look at the tests. Awesome work!!!

**Comment by nosovk** [comment]
@AlxZchk connected version from PR to existing Angular Project, and seems that https://github.com/sclausen/ngx-mqtt/issues/142 fixed by update

**Pull request merged**
