### PR TITLE
Update to Angular6 and use CLI to build the library

### PR DESCRIPTION
**Pull request by chrste90**
Hi,

i updated the library to work with RXJS and Angular 6.

While i was on it, i also updated the library to use the Angular CLI to build and create the output in Angular Package Format.

I hope the changes are welcome, if not, let me know.

It would be nice to release a new version under @next soon if you like the changes.
Actually it is not possible to use the Library with RXJS 6 together.

Thanks,
Chris

### CODE REVIEW

**Comment by chrste90** [comment]
I also updated the tslint.json and replaced it with a standard version of angular cli. If you run `ng lint` there are many warnings. I can fix them in a future pr if you like.

**Comment by sclausen** [comment]
Wow, that's a really comprehensive pull request. Give me some time to review, but a first glance: awesome!

**Comment by chrste90** [comment]
Sure, take your time!

**Comment by chrste90** [comment]
Hi @sclausen,

what is the way moving forward? I saw the discussion in the mqtt.js thread and it looks like the plan is to include mqtt with the browserified bundle to the bundle of this lib?

**Comment by sclausen** [comment]
I currently can't think of another way to get it done. `angular-cli` seems to just doesn't work here.

**Comment by sclausen** [comment]
Many many thanks for your great effort! @chrste90! I'm really sorry that using `angular-cli` as a build-tool doesn't seem to fit for this project.

**Comment by chrste90** [comment]
Yeah, it's too bad. Maybe sometimes in the future it will work.

It would be nice to have a mqtt library without node shims because it increases the bundle size without any benefit.

**Comment by sclausen** [comment]
I already started a browser only port. Something like `mqtt.browser.ts`. It's not trivial to write though, because you have to replace not only process, but also node streams with ReadableStream and WriteableStream. Unfortunately they're not supported by all browsers. Nevertheless, this seems to be a fun task.Am 24.04.2018 09:41 schrieb chrste90 <notifications@github.com>:Yeah, it's too bad. Maybe sometimes in the future it will work.
It would be nice to have a mqtt library without node shims because it increases the bundle size without any benefit.

**Pull request closed without merging**
